language: python
dist: xenial
addons:
  firefox: "68.0.2esr"
env:
  - TEST_SUITE=jenkins
  - TEST_SUITE=harvest1
  - TEST_SUITE=harvest2
python:
  - "3.6"
before_install:
  - pip install --upgrade setuptools pip wheel
script:
  - make $TEST_SUITE
